### ISSUE TITLE
Crashing on load links

### ISSUE THREAD

**Issue by JamieS1211** [FoxDenStudio/FoxGuard#31]
Server always crashing on loading links so was wondering if you could help me. As far as I am aware the only thing I change between starting my server when it worked to when it crashed is that I added a second owner to my main protection handler.

This is the console output (dosn't show in latest.log) - https://i.gyazo.com/aadf390a8e49fb4170b7a0b9c50ad29b.png
This is the crash log - http://pastebin.com/quBN0CeL

Sponge - spongeforge-1.8.9-1808-4.1.0-BETA-1285
Forge - forge-1.8.9-11.15.1.1855-universal
Foxcore - FoxCore-0.8.0-103
Foxguard - FoxGuard-0.18.0-249

If there is any more info I can provide let me know.

**Comment by gravityfox** [comment]
This looks like your filesystem locking the file and not letting foxguard access it. This is probably a Windows specific issue. The current codebase is using a released version of mapDB so this issue shouldn't come up again. However i suggest you use linux, it doesn't have these kinds of issues. xD

**Comment by ghost** [comment]
So, after much time researching about this (see #67), this is our conclusion:

We determined that this error is caused by MapDB not being able to use Random Access Files. This only seems to really occur when the server is being run off of an NFS, which doesn't support this. I am unsure if you are using an NFS, and if you aren't then it probably is something like the server being out of storage space, or not having permissions. There is nothing that we can really do about this, although the upcoming FoxGuard releases no longer use MapDB, so should not have this problem.

If you are using a server hosting company, and you are getting this error, and they say that they are not using NFS to back it, please ask for all the details of whatever they are using and report it.

Thanks for your patience, and we apologize for the inconvenience this has caused.
