### ISSUE TITLE
Item Frames problem with Pokemon

### ISSUE THREAD

**Issue by toxxicjtag** [FoxDenStudio/FoxGuard#43]
Currently running http://puu.sh/rsTBQ/10816a687c.png
and http://puu.sh/rsTCR/40600ebce4.png 

People are able to ruin the stores itemframes. They spawn a pixelmon (5.0.0 Beta 9) and the item frames get destroyed.
How can I block them from throwing pokemon in a region. 

Thanks

**Comment by gravityfox** [comment]
So they're breaking item frames with pokeballs?

I'm pretty sure i can't help you at all. Go blame pixelmon.

**Comment by toxxicjtag** [comment]
Alright.

**Comment by gravityfox** [comment]
well actually, can they break item frames with their bare hands?

You can make it so that item frames can't be broken by anyone or anything EXCEPT admins.

So itemframes breaking is actually handled by `damage entity`, because they are entities. They are not living, however, and `damage entity` covers ALL entities. So you then need to set `damage entity living` separately.

I think I'll make a video about this at some point.
