### ISSUE TITLE
Cannot die in The Void

### ISSUE THREAD

**Issue by mzx987** [FoxDenStudio/FoxGuard#66]
The title describes my current situation.

When you create a simple handler and link it to the region **_wglobal**, and set the passive setting to **Default**, you cannot die in the void (unless you explicitly set the permissions to do so).
Correct me if I'm wrong, but there are issues that occur when something falls into the void indefinitely.

I am unsure if this is intentional, or if this is a bug. Thought I would report it here.
I am currently using the latest version of FoxGuard (v0.20.2) and FoxCore (v0.10.2) on SpongeForge (v5.1.0-BETA-2010) with Minecraft v1.10.2.

**Comment by gravityfox** [comment]
Check your simple handler configuration. You might be denying damage or dying.

Make sure you don't have the invincibility or undying flag set.

The workaround is to use an elevation region instead of _wglobal, with the bounds something like [-10, 300]. That way the invulnerability stops once they fall into the void.

However I will look into adding an exception for falling into the void. This is hilarious though.
